#!/usr/bin/python3
"""REST API for employees todos"""
import requests
import sys


if __name__ == "__main__":
    employeeId = sys.argv[1]
    url = "https://jsonplaceholder.typicode.com/users/" + employeeId
    url_todo = "https://jsonplaceholder.typicode.com/todos?userId=" + employeeId

    response = requests.get(url=url)
    response_t = requests.get(url=url_todo)

    t_response = response_t.json()
    b_response = response.json()
    list_n = []

    for item in t_response:
        if item['completed']:
            list_n.append(item['title'])

    print("Employee {} is done with tasks({}/{}):"
            .format(b_response['name'], len(list_n), len(t_response)))
    for l_item in list_n:
        print("\t{}".format(l_item))
