#!/usr/bin/env bash
# A script that displays Best School bad luck, good luck

i=1

while [ $i -le 10 ]
do
	if [ $i -eq 4 ];
	then
		echo "bad luck"
	elif [ $i -eq 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
